services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: techture_media.settings.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: techture_media
      POSTGRES_USER: techture_media
      POSTGRES_PASSWORD: techture_media
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techture_media"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
