# Generated by Django 5.1.15 on 2026-05-21 15:33

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-slug')),
            ],
            options={
                'verbose_name': 'Blogcategorie',
                'verbose_name_plural': 'Blogcategorieën',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='BlogArtikelPagina',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.CharField(blank=True, help_text='Korte omschrijving voor zoekmachines (max. 160 tekens).', max_length=160, verbose_name='SEO-omschrijving')),
                ('body', wagtail.fields.StreamField([('hero', 6), ('tekst', 8), ('afbeelding', 11), ('twee_kolommen', 14), ('citaat', 18), ('call_to_action', 23), ('video', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titel', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitel', 'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Afbeelding'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Knoptekst', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne link', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Externe link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('titel', 0), ('subtitel', 1), ('afbeelding', 2), ('cta_tekst', 3), ('cta_interne_link', 4), ('cta_externe_link', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote'], 'label': 'Tekst'}), 8: ('wagtail.blocks.StructBlock', [[('inhoud', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Bijschrift', 'max_length': 200, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Alt-tekst', 'max_length': 200, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('afbeelding', 2), ('bijschrift', 9), ('alt_tekst', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote'], 'label': 'Linker kolom'}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote'], 'label': 'Rechter kolom'}), 14: ('wagtail.blocks.StructBlock', [[('linker_kolom', 12), ('rechter_kolom', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Citaat'}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur', 'max_length': 100, 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Functie', 'max_length': 100, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('citaat', 15), ('auteur', 16), ('functie', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Tekst', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Knoptekst', 'max_length': 50}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Knoplink'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Licht'), ('dark', 'Donker'), ('accent', 'Accent')], 'label': 'Stijl'}), 23: ('wagtail.blocks.StructBlock', [[('titel', 0), ('tekst', 19), ('knop_tekst', 20), ('knop_link', 21), ('stijl', 22)]], {}), 24: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Video-URL (YouTube, Vimeo, etc.)'}), 25: ('wagtail.blocks.StructBlock', [[('video', 24), ('bijschrift', 9)]], {})}, verbose_name='Inhoud')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Publicatiedatum')),
                ('auteur', models.CharField(blank=True, max_length=100, verbose_name='Auteur')),
                ('intro', models.TextField(help_text='Wordt getoond in de overzichtskaart en bij zoekresultaten (max. 400 tekens).', max_length=400, verbose_name='Inleiding')),
                ('og_image', models.ForeignKey(blank=True, help_text='Afbeelding voor sociale media (aanbevolen: 1200×630 px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Deelafbeelding (OG)')),
                ('uitgelichte_afbeelding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Uitgelichte afbeelding')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikelen', to='blog.blogcategorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Blogartikel',
                'verbose_name_plural': 'Blogartikelen',
                'ordering': ['-datum'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogOverzichtPagina',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.CharField(blank=True, help_text='Korte omschrijving voor zoekmachines (max. 160 tekens).', max_length=160, verbose_name='SEO-omschrijving')),
                ('body', wagtail.fields.StreamField([('hero', 6), ('tekst', 8), ('afbeelding', 11), ('twee_kolommen', 14), ('citaat', 18), ('call_to_action', 23), ('video', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titel', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitel', 'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Afbeelding'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Knoptekst', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Interne link', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Externe link', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('titel', 0), ('subtitel', 1), ('afbeelding', 2), ('cta_tekst', 3), ('cta_interne_link', 4), ('cta_externe_link', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote'], 'label': 'Tekst'}), 8: ('wagtail.blocks.StructBlock', [[('inhoud', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Bijschrift', 'max_length': 200, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Alt-tekst', 'max_length': 200, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('afbeelding', 2), ('bijschrift', 9), ('alt_tekst', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote'], 'label': 'Linker kolom'}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote'], 'label': 'Rechter kolom'}), 14: ('wagtail.blocks.StructBlock', [[('linker_kolom', 12), ('rechter_kolom', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Citaat'}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Auteur', 'max_length': 100, 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Functie', 'max_length': 100, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('citaat', 15), ('auteur', 16), ('functie', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {'label': 'Tekst', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Knoptekst', 'max_length': 50}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Knoplink'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Licht'), ('dark', 'Donker'), ('accent', 'Accent')], 'label': 'Stijl'}), 23: ('wagtail.blocks.StructBlock', [[('titel', 0), ('tekst', 19), ('knop_tekst', 20), ('knop_link', 21), ('stijl', 22)]], {}), 24: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Video-URL (YouTube, Vimeo, etc.)'}), 25: ('wagtail.blocks.StructBlock', [[('video', 24), ('bijschrift', 9)]], {})}, verbose_name='Inhoud')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introductietekst')),
                ('artikelen_per_pagina', models.PositiveSmallIntegerField(default=9, verbose_name='Artikelen per pagina')),
                ('og_image', models.ForeignKey(blank=True, help_text='Afbeelding voor sociale media (aanbevolen: 1200×630 px).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Deelafbeelding (OG)')),
            ],
            options={
                'verbose_name': 'Blog overzichtspagina',
                'verbose_name_plural': "Blog overzichtspagina's",
            },
            bases=('wagtailcore.page',),
        ),
    ]
